name: Stage the app

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run staging task
        run: echo "Staging workflow triggered because PR was labeled 'stage'"
